### ISSUE TITLE
[FR] Add bake id in job tags

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#310]
FR from Synthesis:
- it would be definitely a useful feature to see Bake ID in jobs tags, which were launched as a part of batch execution.
- bake executor job should be tagged as well
- soon we will have the ability to tag neuro-extras image builder jobs -> need to propagate this feature to neuro-flow

**Comment by romasku** [comment]
Unfortunately, this change breaks our caching logic:
To generate tasks caching key, we hash its contexts (all data that is available to expressions). Also, there is a `tags` context (so you can access tasks tags by using `${{ tags }}`). So if I add "bake_id" to the tags, then the caching key will never match (because bake_id is different for each run).

I see two options, but both of them are not nice:
- do not add "bake_id" to tags context, but mark jobs with this tag. It will work, but it will be harder to implement the third point of this issue.
- add "bake_id" to tags context, but ignore it in caching key calculations. Can't see direct issues, but can be dangerous. Also, I do not like such exceptional rules in general.

As for me, the first option is a little bit better, but let's discuss it.

**Comment by YevheniiSemendiak** [comment]
The feature from Synthesis sounded like "It looks like it would be pretty useful to have bake id in job tags." and I do understand them.

The context: 
- their batch contains ~15 tasks right now and will be more (maybe, up to 20-25)
- they perform several bakes in a row (2-3 bakes -> 40+ running tasks)
- we are planning to add a possibility to run a part of the batch for inference, which will be launched as many times, as the resources allow to do that (once again, a lot of jobs).

Keeping track of which tasks belong to which bake in WebUI (where the list of jobs is displayed), or in CLI becomes really hard -> bake_id tags are needed.
Maybe we have some other approach to solve that problem?

**Comment by romasku** [comment]
I agree with that lookup "raw job" -> "bake" should be easier than just checking all bakes. Tags are a good solution here.

My concern was about allowing a job inside of a bake to know the current bake's id. Because using this can break cache -- if job creates a folder with a name including bake_id, or tag an image using it, then the cached result can be invalid for a subsequent run with a different bake_id.

Anyway, personally, now I think we can live with that. Anyone can just use "random()" inside the task and it can break the cache. So if someone uses bake_id, it will be his responsibility to make sure that cache is valid.

**Comment by YevheniiSemendiak** [comment]
Agree with you, the one who refers to random things in their workload already do the mistake, but we will not be able to protect them from anything like this.
So, what is the decision here?
