### ISSUE TITLE
Bake action is reported as "succeeded" even if underlying tasks were "cancelled" and skipped.

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#316]
The bug reported by the Synthesis team.

There is a batch, which contains several actions, one of them is the `model_check` action, which contains two tasks: `model_check.build_image` -> `model_check.model_check`.

The bake execution was cancelled somewhere during 1st task execution within this action. (due to some other task's failure)
As a result, the first task was marked as "Cancelled" (which is correct), second task - "Skipped" (correct), but the action itself was marked as "Succeeded", which is incorrect.

![image](https://user-images.githubusercontent.com/32543098/111510358-5fda2080-8756-11eb-98e5-41cbb578f929.png)

This is confusing and definitely should be fixed.

**Comment by romasku** [comment]
I can explain some logic about this behavior. When we calculate the action result status and its outputs, we only check tasks that are specified as [outputs.needs](https://neu-ro.gitbook.io/neuro-flow/reference/actions-syntax#outputs-needs). By default, this is the empty list. So in this case we consider action succeeded as all (empty set) depending tasks are completed successfully.

I agree that this is not obvious at all, but I cannot see a simple rule here. Imagine the following situation:

> Action has two tasks, the first succeded, and the second one was canceled. It only requires the first task to generate outputs (outputs.needs == ['task1']).
 1. Should we mark the action as canceled or as succeeded? 
 2. What status should see a task marked with `always()` (executed even after cancelation) if it depends on the action? Should it be able to access outputs?
 3. If the second task is failed instead of canceled, what status action should get? Can it be some unimportant task that is flaky and isn't required?
 
For me, the correct answer is "succeeded" for all cases, because the action developer explicitly specified that only the first task is required.
 
I think the core problem in your case is that when the action does not define `outputs.needs` it defaults to an empty array. This leads to behavior where the action will always receive a "succeeded" state. So, as for me, setting an empty list as default was a mistake (it is my mistake by the way). I suggest that we change the default to "all action tasks". Then, if some tasks should be defined as optional, the developer will have to explicitly say that. 

@asvetlov What do you think about this? Is it worse to break backward compatibility because of this issue?

**Comment by YevheniiSemendiak** [comment]
> I suggest that we change the default to "all action tasks"

Totally agree with you 👍 

Re "enforcing `outputs.needs` field appearance" - I don't really like this approach, tbh.. 

@mariyadavydova , @adavydow wdyt?

**Comment by romasku** [comment]
I found that we have almost the same issue when we select a status for a bake itself. At the moment it has the following rules:
- If any of the top-level tasks are failed, then bake is failed.
- If any of the top-level tasks were cancelled, then bake is cancelled.
- Otherwise bake is succeeded.
For a bake, there is no way to specify "required to succeed" tasks, so I think we shouldn't touch it. Then we can apply the same for actions to be consistent:
- If any of the action tasks (no meter, is it present in `outputs.needs`) failed - the action is failed.
- If any of the action tasks (no meter, is it present in `outputs.needs`) canceled - the action is canceled.
- otherwise, the action is succeeded.
I feel like it also follows the "fail early" mantra - if some task failed, we should fail the batch. I do not like my idea about the optional flaky task from the above message anymore.

**Comment by YevheniiSemendiak** [comment]
> we can apply the same for actions to be consistent

Sounds reasonable, I like that. (Indeed, why would you allow a task to fail within a pipeline/action in most ML pipeline cases? If you allow them to fail - you will need to handle that within a task, but the overall task should be succeeded in any case.)
