### ISSUE TITLE
Global options should be passed to remote executor

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#345]
Such CLI global options as:
- `-v, --verbose`
- `-q, --quiet`
- `--show-traceback`
are not [passed](https://github.com/neuro-inc/neuro-flow/blob/master/neuro_flow/batch_runner.py#L205-L208) to the remote executor even if they are used in local CLI.
The last one might be useful for debugging by the internal team, for instance, the following errors:
![image](https://user-images.githubusercontent.com/32543098/113432745-9ff00300-93e6-11eb-90f0-d9c9f385e353.png)

Neuro Platform Client 21.4.1
neuro-flow package version: 21.3.17

**Comment by romasku** [comment]
Good idea, we'll implement it!

Just for your knowledge, it will have almost no effect on the latest version because of this [PR](https://github.com/neuro-inc/neuro-flow/pull/338). More precisely, this code:
```
        with self._progress:
            try:
                result = await self._run()
            except (KeyboardInterrupt, asyncio.CancelledError):
                await self._cancel_unfinished()
                result = TaskStatus.CANCELLED
            except Exception as exp:
                await self.log_error(exp)
                await self._cancel_unfinished()
                result = TaskStatus.FAILED
        await self._finish_run(result)
```
Catches all errors that happen inside the executor. The `log_error`prints tracebacks for all exceptions except `EvalError`. So all unknown errors (like `Server disconnected`) are already logged with details in the latest version of neuro flow.
