### ISSUE TITLE
Cancel bake does not stop executor and bake tasks

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#440]
The bake itself gets into the "Cancelled" state.
However, the executor and all its tasks are continuing to run, new tasks are starting too.

neuro-flow package version: 21.5.25

![image](https://user-images.githubusercontent.com/32543098/119964013-66d0ab00-bfb1-11eb-9dc6-f3db57026464.png)

**Comment by romasku** [comment]
Did the executor completely ignored cancelation or just reacted to it with some delay?

Currently, bake cancelation isn't immediate (we cannot kill the executor job directly because it will break `if: ${{always()}}` tasks). Executor checks the bake status periodically, so it can happen that it will start a new task before noticing cancellation.

**Comment by YevheniiSemendiak** [comment]
I was waiting not for really long (a couple of minutes, tbh).
> Executor checks the bake status periodically,

How often does it happen? I mean, what's the maximal interval of time we should wait before the executor kills the tasks and dies itself?

**Comment by romasku** [comment]
I think at most 10-20 seconds in the worst case. It should be a couple of seconds in most cases. I currently cannot cancel bake to test because of some error, I'll try to find out what has happenned.

**Comment by romasku** [comment]
Found a bug, this is due to caching we use on the client. This caching is only a temporary step while we migrate from storage-based API.
